<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BudgetWise.Core\BudgetWise.Core.csproj" />
    <ProjectReference Include="..\BudgetWise.Shared\BudgetWise.Shared.csproj" />
  </ItemGroup>

</Project>
